### PR TITLE
fix: Drop single events if corrupted instead of failing whole import

### LINKED ISSUE #162: Importing of buckets with invalid utf-8 strings fails
I once visited a website which on purpose created invalid utf-16 strings in the title. This should be very rare as this site went to great lengths with messing up the characters (it essentially did so to be artistic, the site is virtualself.co)

When I try to import such buckets from aw-server-python to aw-server-rust it fails with the following

thread '<unnamed>' panicked at 'Failed to deserialize import data as JSON to bucket format: Error("unexpected end of hex escape", line: 24, column: 291)', aw-server/src/endpoints/import.rs:61:38

If someone wants to reproduce this is a minimal export file:

```
{
    "buckets": {
        "my-test-bucket": {
            "id": "my-test-bucket",
            "hostname": "johan-desktop",
            "client": "test-client",
            "created": "2020-01-28T12:43:29.137000+00:00",
            "type": "test",
            "events": [
                {
                    "timestamp": "2020-01-28T12:43:14.141000+00:00",
                    "duration": 4.993,
                    "data": {
                        "url": "https://virtualself.co/",
                        "title": "\ud835\udc47\ud835\ude29\ud835\udc56\ud835\udc60 \ud835\udc64\ud835\udc56\ud835\udc59\ud835\udc59 \ud835\udc4f\ud835\udc52\ud835\udc50\ud835\udc5c\ud835\udc5a\ud835\udc52 \ud835\udc61\ud835\ude29\ud835\udc52 \ud835\udc53\ud835\udc56\ud835\udc5b\ud835\udc4e\ud835\udc59 \ud835\udc5d\ud835\udc4e\ud835\udc5f\ud835\udc61\ud835\udc56\ud835\udc50\ud835\udc59\ud835\udc52-\ud835\udc38\ud835\udc65\ud835\udc5d\ud835\udc52\ud835\udc5f\ud835",
                        "audible": true,
                        "incognito": false,
                        "tabCount": 57
                    }
                }
            ]
        }
    }
}
```

### PR DESCRIPTION
**Pull request by johan-bjareholt**
Fixes #162 

Todo:
- [x] More manual testing
- [x] Infinite loop on some types
- [x] A few TODO comments
- [x] Fix schema

### CODE REVIEW

**Comment by johan-bjareholt** [comment]
After some more tests I realized that this is broken. Do not merge.

**Comment by johan-bjareholt** [comment]
@ErikBjare Works as it should now, schema is still broken because I added these "wrapper" objects to handling deserialization which are seen in the schema. It's only for bucket where "events" are optional anyway.

File: aw-datastore/src/legacy_import.rs [hunk 1]
```diff
@@ -139,7 +116,35 @@ mod import {
...
+
+                    let data: serde_json::map::Map<String, serde_json::Value> =
+                        match serde_json::from_str(&data_str) {
+                            Ok(data) => data,
+                            Err(err) => {
+                                warn!(
+                                    "Unable to parse JSON data in event from bucket {}\n{}\n{}",
+                                    bucket_id, err, data_str
+                                );
+                                continue;
```
Comment (ErikBjare) [inline aw-datastore/src/legacy_import.rs:136]: I'd prefer if the invalid string in question was replaced with "invalid" or something instead of just skipped with a warning, but no biggie.

**Review by ErikBjare — APPROVED** [review]
Looks good to me, although might want to sprinkle some comments with references to relevant issues.

Any chance the schema could be fixed?

**Comment by johan-bjareholt** [comment]
The schema has improved now.

The "Event" is wrapped inside what I call a "Try<aw_models::event::Event>" openapi definition unfortunately, but that definition is perfectly exact now at least and could theoretically be used for validation.
