### PR TITLE
fix: If events merge during flood, choose the longest endtime

### LINKED ISSUE #140: Significant differences between reporting of aw-server and aw-server-rust
I looked at my events for a day a month ago, and there are a couple of significant differences between what aw-server-rust and what aw-server reports.

Not sure if it's due to the migration or one/multiple transform issues.

1. Individual application time:

| Application |  aw-server | aw-server-rust |
| --- | --- | --- |
| Firefox       | 48m26s   | 46m38s           |
| Chromium | 38m41s    | 9m31s            |
|Gedit|9m|8m57s|
|Guake|1m|1m35s|
|Unknown|14s|15s|

*Note*: Individual application time seems to vary everywhere, and in all of the tabs.

2. Total Active time

 |  aw-server | aw-server-rust |
| --- | ---- | 
| 1h 38min | 1hr 6 min |

3. Active browser time in Browser tab:

|   aw-server | aw-server-rust |
| ---- | ---- |
|  1 hr 21 min | 52 min |

**Another potential bug**: If you sum up ALL of the times for each browser domain, they won't be equal to the total active browser time for aw-server-rust. This issue doesn't occur for aw-server. 

4. Top categories amounts are also all very different between the 2 servers. This however, is expected given point 1.

4. Timelines look the same(from a high level view)

OS: Fedora 32, Gnome 3.36, Xorg

### PR DESCRIPTION
**Pull request by johan-bjareholt**
Fixes #140

### CODE REVIEW

File: aw-transform/src/flood.rs [hunk 1]
```diff
@@ -36,8 +36,15 @@ pub fn flood(events: Vec<Event>, pulsetime: chrono::Duration) -> Vec<Event> {
                     warn!("Gap was of negative duration ({}s), but could be safely merged. This error will only show once per batch.", gap);
                     warned_negative_gap_safe = true;
                 }
-                // Extend e1 to the middle between e1 and e2
-                e1.duration = e2.calculate_endtime() - e1.timestamp;
+                // Choose the longest event and set the endtime to it
+                // TODO: Also possibly extend to an e3 if that exists?
```
Comment (ErikBjare) [inline aw-transform/src/flood.rs:40]: Hmm, I thought the Python version would do this too, but maybe it doesn't?

File: aw-transform/src/flood.rs [hunk 2]
```diff
@@ -126,4 +132,37 @@ mod tests {
         assert_eq!(&res[0], &e1_expected);
         assert_eq!(&res[1], &e2_expected);
     }
+
+    #[test]
+    fn test_flood_same_timestamp() {
+        let e1 = Event {
+            id: None,
+            timestamp: DateTime::from_str("2020-06-16T03:29:11.334000+00:00").unwrap(),
+            duration: Duration::microseconds(305402078),
```
Comment (ErikBjare) [inline aw-transform/src/flood.rs:141]: It's a bit hard to read these tests when you involve millisecond-precision. Would be nicer with round datetimes.

Comment (johan-bjareholt) [reply aw-transform/src/flood.rs]: Sorry, my bad. Was copied straight from a real broken example.
Fixed.

File: aw-transform/src/flood.rs (hunk 1 above)
Comment (johan-bjareholt) [reply aw-transform/src/flood.rs:40]: I'm not sure if I'm reading the code correctly, but this is how it works I think.

It iterates over the events with zip which creates an array in the form of `[[1,2],[2,3],[3,4]]`, but if it sees a change to merge an event it extends the first event to the end of the second one and sets the duration of the second one to 0 and afterwards filter out all events with an duration of 0. So that means that today it "kind of" works because it will not merge the same event over and over but create multiple merged events even if they have the same data and could be merged, but it would be easy to fix by simply extending the second event instead of the first one so on the next iteration it would have an event which does not have a duration of 0.

Comment (johan-bjareholt) [reply aw-transform/src/flood.rs]: In the latest commit I have fixed it.

File: aw-transform/src/flood.rs [hunk 3]
```diff
@@ -36,25 +38,36 @@ pub fn flood(events: Vec<Event>, pulsetime: chrono::Duration) -> Vec<Event> {
...
+                }
                 // Drop next event since they are merged and flooded into e1
-                drop_next = true;
+                e1_iter.next();
+                // Retry this event again to give it a change to merge e1
+                // with 'e3'
+                retry_e = Some(e1);
+                // Since we are retrying on this event we don't want to push it
+                // to the new_events vec
+                continue;
```
Comment (ErikBjare) [inline aw-transform/src/flood.rs:56]: Cool! Took me a while to understand what's going on with `retry_e`, but looks performant :smiley:

Comment (johan-bjareholt) [reply aw-transform/src/flood.rs:56]: It's mostly to make the borrow checker happy, there are more readable ways to implement it if you write "unsafe" code.
